default_language_version:
    python: python3
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      entry: flake8 src tests
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        entry: black src tests
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
